# Site settings
title: "EdgeBit"
email: "help@edgebit.co.kr"
description: > # this means to ignore newlines until "baseurl:"
  
  
  .
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://edgebit.co.kr" # the base hostname & protocol for your site
twitter_username: ""
github_username:  ""

# Build settings
markdown: kramdown
encoding: "utf-8"

defaults:
 -
   scope:
    path: _posts/en
   values:
    layout: default
    lang: en
 -
   scope:
    path: _posts/kr
   values:
    layout: default
    lang: kr

permalink: /:title/